// services/core/logic/engine29/tacticalCharacter/moveCharacterConstants.js

export const ENGINE29_MOVE_DIRECTIONS = Object.freeze({
  UP: "UP",
  DOWN: "DOWN",
  FLAT: "FLAT",
  MIXED: "MIXED",
});

export const ENGINE29_MOVE_CHARACTERS = Object.freeze({
  NO_ACTIVE_MOVE: "NO_ACTIVE_MOVE",
  BROAD_MOVE_CONFIRMED: "BROAD_MOVE_CONFIRMED",
  POSSIBLE_UPSIDE_SQUEEZE: "POSSIBLE_UPSIDE_SQUEEZE",
  POSSIBLE_DOWNSIDE_SQUEEZE: "POSSIBLE_DOWNSIDE_SQUEEZE",
  LIQUIDITY_SWEEP_HIGH: "LIQUIDITY_SWEEP_HIGH",
  LIQUIDITY_SWEEP_LOW: "LIQUIDITY_SWEEP_LOW",
  FAILED_BREAKOUT: "FAILED_BREAKOUT",
  FAILED_BREAKDOWN: "FAILED_BREAKDOWN",
  MIXED: "MIXED",
});

export const ENGINE29_MOVE_REASON_CODES = Object.freeze({
  HEADLINE_UP_IMPULSE: "HEADLINE_UP_IMPULSE",
  HEADLINE_DOWN_IMPULSE: "HEADLINE_DOWN_IMPULSE",
  HEADLINE_MIXED: "HEADLINE_MIXED",

  BREADTH_CONFIRMS_MOVE: "BREADTH_CONFIRMS_MOVE",
  BREADTH_NOT_CONFIRMING: "BREADTH_NOT_CONFIRMING",
  LEADERSHIP_CONFIRMS_MOVE: "LEADERSHIP_CONFIRMS_MOVE",
  LEADERSHIP_NOT_CONFIRMING: "LEADERSHIP_NOT_CONFIRMING",
  CREDIT_CONFIRMS_MOVE: "CREDIT_CONFIRMS_MOVE",
  CREDIT_NOT_CONFIRMING: "CREDIT_NOT_CONFIRMING",

  ONE_HOUR_STRESS_STILL_ACTIVE: "ONE_HOUR_STRESS_STILL_ACTIVE",
  ONE_HOUR_CONTEXT_OPPOSES_FAST_MOVE: "ONE_HOUR_CONTEXT_OPPOSES_FAST_MOVE",

  SWEEP_ABOVE_RESISTANCE_FAILED_HOLD: "SWEEP_ABOVE_RESISTANCE_FAILED_HOLD",
  SWEEP_BELOW_SUPPORT_FAILED_HOLD: "SWEEP_BELOW_SUPPORT_FAILED_HOLD",
  BREAKOUT_FAILED_RECLAIM: "BREAKOUT_FAILED_RECLAIM",
  BREAKDOWN_FAILED_RECLAIM: "BREAKDOWN_FAILED_RECLAIM",

  BROAD_CONFIRMATION_PRESENT: "BROAD_CONFIRMATION_PRESENT",
  BROAD_CONFIRMATION_MISSING: "BROAD_CONFIRMATION_MISSING",
  DIRECT_VOLATILITY_CONFIRMATION_MISSING: "DIRECT_VOLATILITY_CONFIRMATION_MISSING",
});

export const ENGINE29_MOVE_CHARACTER_DEFAULTS = Object.freeze({
  headlineBarsBack: 2,
  baselineBars: 40,
  minHeadlineAbsMovePct: 0.12,
  minHeadlineImpulseMultiple: 1.5,
  minInternalDirectionalPct: 0.03,
  internalBaselineFraction: 0.5,
  minSweepExcursionPct: 0.03,
  sweepRangeFraction: 0.25,
});
