// services/core/logic/engine29/canonical/reasonCodes.js

export const ENGINE29_REASON_CODES = Object.freeze({
  // Data quality / feed integrity
  DATA_REQUIRED_SYMBOL_MISSING: "DATA_REQUIRED_SYMBOL_MISSING",
  DATA_REQUIRED_SYMBOL_STALE: "DATA_REQUIRED_SYMBOL_STALE",
  DATA_PROXY_IN_USE: "DATA_PROXY_IN_USE",
  DATA_PARTIAL_GROUP: "DATA_PARTIAL_GROUP",

  // Headline indexes
  HEADLINE_SPX_BREAKDOWN: "HEADLINE_SPX_BREAKDOWN",
  HEADLINE_SPY_BREAKDOWN: "HEADLINE_SPY_BREAKDOWN",
  HEADLINE_NDX_BREAKDOWN: "HEADLINE_NDX_BREAKDOWN",
  HEADLINE_QQQ_BREAKDOWN: "HEADLINE_QQQ_BREAKDOWN",

  // Breadth
  BREADTH_IWM_BREAKDOWN: "BREADTH_IWM_BREAKDOWN",
  BREADTH_MDY_BREAKDOWN: "BREADTH_MDY_BREAKDOWN",
  BREADTH_RSP_BREAKDOWN: "BREADTH_RSP_BREAKDOWN",
  BREADTH_CONFIRMED: "BREADTH_CONFIRMED",

  // Leadership
  LEADERSHIP_SMH_BREAKDOWN: "LEADERSHIP_SMH_BREAKDOWN",
  LEADERSHIP_SOX_BREAKDOWN: "LEADERSHIP_SOX_BREAKDOWN",
  LEADERSHIP_XLK_BREAKDOWN: "LEADERSHIP_XLK_BREAKDOWN",
  LEADERSHIP_SEMICONDUCTOR_BLOCK_CONFIRMED:
    "LEADERSHIP_SEMICONDUCTOR_BLOCK_CONFIRMED",
  LEADERSHIP_CONFIRMED: "LEADERSHIP_CONFIRMED",

  // Credit
  CREDIT_HYG_BREAKDOWN: "CREDIT_HYG_BREAKDOWN",
  CREDIT_JNK_BREAKDOWN: "CREDIT_JNK_BREAKDOWN",
  CREDIT_LQD_BREAKDOWN: "CREDIT_LQD_BREAKDOWN",
  CREDIT_XLF_BREAKDOWN: "CREDIT_XLF_BREAKDOWN",
  CREDIT_KRE_BREAKDOWN: "CREDIT_KRE_BREAKDOWN",
  CREDIT_HIGH_YIELD_CONFIRMED: "CREDIT_HIGH_YIELD_CONFIRMED",
  CREDIT_CONFIRMED: "CREDIT_CONFIRMED",

  // Rates / duration
  RATES_10Y_BREAKOUT: "RATES_10Y_BREAKOUT",
  RATES_30Y_BREAKOUT: "RATES_30Y_BREAKOUT",
  TLT_DURATION_BREAKDOWN: "TLT_DURATION_BREAKDOWN",
  RATES_DURATION_CONFIRMED: "RATES_DURATION_CONFIRMED",

  // Energy / inflation
  WTI_BREAKOUT: "WTI_BREAKOUT",
  BRENT_BREAKOUT: "BRENT_BREAKOUT",
  ENERGY_OIL_COMPLEX_CONFIRMED: "ENERGY_OIL_COMPLEX_CONFIRMED",

  // Volatility
  VIX_FIRMING: "VIX_FIRMING",
  VIX_BREAKOUT: "VIX_BREAKOUT",
  VIX_STRESS_EXPANSION: "VIX_STRESS_EXPANSION",

  // Financial conditions
  DXY_FINANCIAL_CONDITIONS_TIGHTENING:
    "DXY_FINANCIAL_CONDITIONS_TIGHTENING",
  FINANCIAL_CONDITIONS_NFCI_WORSENING:
    "FINANCIAL_CONDITIONS_NFCI_WORSENING",
  FINANCIAL_CONDITIONS_STLFSI_WORSENING:
    "FINANCIAL_CONDITIONS_STLFSI_WORSENING",
  FINANCIAL_CONDITIONS_CREDIT_SPREAD_WIDENING:
    "FINANCIAL_CONDITIONS_CREDIT_SPREAD_WIDENING",

  // Overall state transitions
  OVERALL_EARLY_WARNING: "OVERALL_EARLY_WARNING",
  OVERALL_BROAD_DETERIORATION: "OVERALL_BROAD_DETERIORATION",
  OVERALL_RISK_OFF_CONFIRMED: "OVERALL_RISK_OFF_CONFIRMED",
  OVERALL_SYSTEMIC_STRESS: "OVERALL_SYSTEMIC_STRESS",
  OVERALL_STRESS_DOWNGRADE: "OVERALL_STRESS_DOWNGRADE",
  OVERALL_RECOVERY_IN_PROGRESS: "OVERALL_RECOVERY_IN_PROGRESS",
});

export function isEngine29ReasonCode(value) {
  return Object.values(ENGINE29_REASON_CODES).includes(value);
}
