// services/core/logic/engine29/aggregate/overallStateConstants.js

export const ENGINE29_FAST_SHIFT_STATES = Object.freeze({
  NEUTRAL: "NEUTRAL",
  STABILIZING: "STABILIZING",
  RECOVERY_ATTEMPT: "RECOVERY_ATTEMPT",
  BUYING_PRESSURE_INCREASING: "BUYING_PRESSURE_INCREASING",
  SELLING_PRESSURE_INCREASING: "SELLING_PRESSURE_INCREASING",
  POSSIBLE_UPSIDE_SQUEEZE: "POSSIBLE_UPSIDE_SQUEEZE",
  POSSIBLE_DOWNSIDE_SQUEEZE: "POSSIBLE_DOWNSIDE_SQUEEZE",
  LIQUIDITY_SWEEP_HIGH: "LIQUIDITY_SWEEP_HIGH",
  LIQUIDITY_SWEEP_LOW: "LIQUIDITY_SWEEP_LOW",
  BROAD_MOVE_UP: "BROAD_MOVE_UP",
  BROAD_MOVE_DOWN: "BROAD_MOVE_DOWN",
  MIXED: "MIXED",
});

export const ENGINE29_ALERT_TYPES = Object.freeze({
  STATE_UPGRADE: "STATE_UPGRADE",
  STATE_DOWNGRADE: "STATE_DOWNGRADE",
  TACTICAL_CHANGE: "TACTICAL_CHANGE",
  MOVE_CHARACTER_CHANGE: "MOVE_CHARACTER_CHANGE",
  LIQUIDITY_EVENT: "LIQUIDITY_EVENT",
  DATA_QUALITY_CHANGE: "DATA_QUALITY_CHANGE",
});

export const ENGINE29_PHASE5_REASON_CODES = Object.freeze({
  STRUCTURAL_NORMAL: "STRUCTURAL_NORMAL",
  STRUCTURAL_EARLY_WARNING: "STRUCTURAL_EARLY_WARNING",
  STRUCTURAL_BROAD_DETERIORATION: "STRUCTURAL_BROAD_DETERIORATION",
  STRUCTURAL_RISK_OFF_CONFIRMED: "STRUCTURAL_RISK_OFF_CONFIRMED",
  STRUCTURAL_SYSTEMIC_STRESS: "STRUCTURAL_SYSTEMIC_STRESS",

  INTERNALS_CONFIRMED: "INTERNALS_CONFIRMED",
  MULTIPLE_INDEPENDENT_GROUPS_CONFIRMED: "MULTIPLE_INDEPENDENT_GROUPS_CONFIRMED",
  CREDIT_PROMOTION_GATE_MET: "CREDIT_PROMOTION_GATE_MET",
  CREDIT_PROMOTION_GATE_MISSING: "CREDIT_PROMOTION_GATE_MISSING",
  VOLATILITY_CONFIRMATION_MET: "VOLATILITY_CONFIRMATION_MET",
  VOLATILITY_CONFIRMATION_MISSING: "VOLATILITY_CONFIRMATION_MISSING",
  HEADLINE_BREAK_CONFIRMED: "HEADLINE_BREAK_CONFIRMED",
  FINANCIAL_CONDITIONS_CONFIRMATION_MISSING: "FINANCIAL_CONDITIONS_CONFIRMATION_MISSING",

  TACTICAL_NORMAL: "TACTICAL_NORMAL",
  TACTICAL_CAUTION: "TACTICAL_CAUTION",
  TACTICAL_RISK_OFF_ACTIVE: "TACTICAL_RISK_OFF_ACTIVE",
  TACTICAL_STRESS_ACCELERATING: "TACTICAL_STRESS_ACCELERATING",
  TACTICAL_RECOVERING: "TACTICAL_RECOVERING",

  FAST_SHIFT_RECOVERY_ATTEMPT: "FAST_SHIFT_RECOVERY_ATTEMPT",
  FAST_SHIFT_SELLING_PRESSURE: "FAST_SHIFT_SELLING_PRESSURE",
  FAST_SHIFT_BUYING_PRESSURE: "FAST_SHIFT_BUYING_PRESSURE",
  FAST_SHIFT_STABILIZING: "FAST_SHIFT_STABILIZING",
});
