// services/core/logic/engine29/constants.js

export const ENGINE29_VERSION = "engine29.crossMarketStress.v1";

export const ENGINE29_TIMEFRAMES = Object.freeze({
  STRUCTURAL: "1W",
  TACTICAL: "1H",
  FAST_TACTICAL: "30m",
  FUTURE_FAST_TACTICAL: "30m", // legacy alias
});

export const ENGINE29_OVERALL_STATES = Object.freeze({
  NORMAL: "NORMAL",
  EARLY_WARNING: "EARLY_WARNING",
  BROAD_DETERIORATION: "BROAD_DETERIORATION",
  RISK_OFF_CONFIRMED: "RISK_OFF_CONFIRMED",
  SYSTEMIC_STRESS: "SYSTEMIC_STRESS",
});

export const ENGINE29_SYMBOL_STATES = Object.freeze({
  HEALTHY: "HEALTHY",
  WARNING: "WARNING",
  BREAKING: "BREAKING",
  CONFIRMED_BREAK: "CONFIRMED_BREAK",
  RECOVERING: "RECOVERING",
});

export const ENGINE29_GROUP_STATES = Object.freeze({
  HEALTHY: "HEALTHY",
  FORMING: "FORMING",
  CONFIRMED: "CONFIRMED",
  SEVERE: "SEVERE",
  RECOVERING: "RECOVERING",
});

export const ENGINE29_BACKDROP_STATES = Object.freeze({
  SUPPORTIVE: "SUPPORTIVE",
  NEUTRAL: "NEUTRAL",
  NEGATIVE: "NEGATIVE",
  SEVERELY_NEGATIVE: "SEVERELY_NEGATIVE",
});

export const ENGINE29_TACTICAL_STATES = Object.freeze({
  NORMAL: "NORMAL",
  CAUTION: "CAUTION",
  RISK_OFF_ACTIVE: "RISK_OFF_ACTIVE",
  STRESS_ACCELERATING: "STRESS_ACCELERATING",
  RECOVERING: "RECOVERING",
});

export const ENGINE29_STRESS_DIRECTIONS = Object.freeze({
  LOWER: "LOWER",
  HIGHER: "HIGHER",
  CONTEXTUAL: "CONTEXTUAL",
});

export const ENGINE29_EVIDENCE_QUALITY = Object.freeze({
  DIRECT: "DIRECT",
  PROXY: "PROXY",
  STALE: "STALE",
  PARTIAL: "PARTIAL",
  MISSING: "MISSING",
});

export const ENGINE29_CONFIDENCE = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
});

export const ENGINE29_GROUP_IDS = Object.freeze({
  HEADLINE_INDEX: "HEADLINE_INDEX",
  BREADTH: "BREADTH",
  LEADERSHIP: "LEADERSHIP",
  CREDIT: "CREDIT",
  RATES_DURATION: "RATES_DURATION",
  ENERGY_INFLATION: "ENERGY_INFLATION",
  VOLATILITY: "VOLATILITY",
  FINANCIAL_CONDITIONS: "FINANCIAL_CONDITIONS",
});

export const ENGINE29_GROUP_ORDER = Object.freeze([
  ENGINE29_GROUP_IDS.HEADLINE_INDEX,
  ENGINE29_GROUP_IDS.BREADTH,
  ENGINE29_GROUP_IDS.LEADERSHIP,
  ENGINE29_GROUP_IDS.CREDIT,
  ENGINE29_GROUP_IDS.RATES_DURATION,
  ENGINE29_GROUP_IDS.ENERGY_INFLATION,
  ENGINE29_GROUP_IDS.VOLATILITY,
  ENGINE29_GROUP_IDS.FINANCIAL_CONDITIONS,
]);

export const ENGINE29_ARCHITECTURE_RULES = Object.freeze({
  structuralTimeframe: ENGINE29_TIMEFRAMES.STRUCTURAL,
  tacticalTimeframe: ENGINE29_TIMEFRAMES.TACTICAL,
  fastTacticalTimeframe: ENGINE29_TIMEFRAMES.FAST_TACTICAL,
  futureFastTacticalTimeframe: ENGINE29_TIMEFRAMES.FUTURE_FAST_TACTICAL,
  tacticalCannotOverwriteStructural: true,
  fastTacticalCannotOverwriteTactical: true,
  groupFirstAggregation: true,
  avoidCorrelatedDoubleCounting: true,
  creditPromotionGate: true,
  volatilityConfirmationLayer: true,
  coreLogicLivesOutsideBuildStrategySnapshot: true,
});
