// services/core/logic/engine29/trapDetection/trapConstants.js
// Engine 29 — three-lane market-character vocabulary.
//
// LIQUIDITY = what meaningful level is being tested/taken?
// MOVE CHARACTER = what kind of directional move is occurring?
// TRAP = did the auction fail after liquidity was taken?
//
// Observation / confirmation only. No execution or permission authority.

export const ENGINE29_TRAP_SIDES = Object.freeze({
  NONE: "NONE",
  BULL: "BULL",
  BEAR: "BEAR",
});

export const ENGINE29_LIQUIDITY_EVENT_STATES = Object.freeze({
  NO_LIQUIDITY_EVENT: "NO_LIQUIDITY_EVENT",
  TEST_HIGH: "TEST_HIGH",
  TEST_LOW: "TEST_LOW",
  SWEEP_HIGH: "SWEEP_HIGH",
  SWEEP_LOW: "SWEEP_LOW",
  RECLAIMED_HIGH: "RECLAIMED_HIGH",
  RECLAIMED_LOW: "RECLAIMED_LOW",
});

export const ENGINE29_TRAP_STATES = Object.freeze({
  NO_ACTIVE_TRAP: "NO_ACTIVE_TRAP",
  TRAP_WATCH: "TRAP_WATCH",
  TRAP_FORMING: "TRAP_FORMING",
  TRAP_CONFIRMED: "TRAP_CONFIRMED",
  RESOLVING: "RESOLVING",
  INVALIDATED: "INVALIDATED",
});

export const ENGINE29_AUCTION_RESULTS = Object.freeze({
  NO_ACTIVE_AUCTION: "NO_ACTIVE_AUCTION",
  TESTING_HIGH: "TESTING_HIGH",
  TESTING_LOW: "TESTING_LOW",
  SWEPT_HIGH: "SWEPT_HIGH",
  SWEPT_LOW: "SWEPT_LOW",
  FAILED_ACCEPTANCE_HIGH: "FAILED_ACCEPTANCE_HIGH",
  FAILED_ACCEPTANCE_LOW: "FAILED_ACCEPTANCE_LOW",
  ACCEPTING_ABOVE: "ACCEPTING_ABOVE",
  ACCEPTING_BELOW: "ACCEPTING_BELOW",
});

export const ENGINE29_TRAP_LOCATION_QUALITY = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  VERY_HIGH: "VERY_HIGH",
  UNAVAILABLE: "UNAVAILABLE",
});

export const ENGINE29_LIQUIDITY_LEVEL_TYPES = Object.freeze({
  INSTITUTIONAL_ZONE: "INSTITUTIONAL_ZONE",
  FOUR_HOUR_SWING_HIGH: "FOUR_HOUR_SWING_HIGH",
  FOUR_HOUR_SWING_LOW: "FOUR_HOUR_SWING_LOW",
  TWO_HOUR_SWING_HIGH: "TWO_HOUR_SWING_HIGH",
  TWO_HOUR_SWING_LOW: "TWO_HOUR_SWING_LOW",
  ONE_HOUR_SWING_HIGH: "ONE_HOUR_SWING_HIGH",
  ONE_HOUR_SWING_LOW: "ONE_HOUR_SWING_LOW",
  PRIOR_SESSION_HIGH: "PRIOR_SESSION_HIGH",
  PRIOR_SESSION_LOW: "PRIOR_SESSION_LOW",
  OVERNIGHT_HIGH: "OVERNIGHT_HIGH",
  OVERNIGHT_LOW: "OVERNIGHT_LOW",
  THIRTY_MIN_SWING_HIGH: "THIRTY_MIN_SWING_HIGH",
  THIRTY_MIN_SWING_LOW: "THIRTY_MIN_SWING_LOW",
});

export const ENGINE29_TRAP_REASON_CODES = Object.freeze({
  INSTITUTIONAL_ZONE_NEARBY: "INSTITUTIONAL_ZONE_NEARBY",
  FOUR_HOUR_LIQUIDITY_NEARBY: "FOUR_HOUR_LIQUIDITY_NEARBY",
  TWO_HOUR_LIQUIDITY_NEARBY: "TWO_HOUR_LIQUIDITY_NEARBY",
  ONE_HOUR_LIQUIDITY_NEARBY: "ONE_HOUR_LIQUIDITY_NEARBY",
  MULTI_LEVEL_CONFLUENCE: "MULTI_LEVEL_CONFLUENCE",
  MACRO_LOCATION_UNAVAILABLE: "MACRO_LOCATION_UNAVAILABLE",
});
