// src/services/core/jobs/updateSmzShelves.js
// Smart Money Shelves Job — writes smz-shelves.json (blue/red shelves)
//
// ✅ NOW MATCHES "INSTITUTION STYLE" BEHAVIOR (LOCKED):
// - Auto shelves generated by scanner
// - Manual shelves loaded from data/smz-manual-shelves.json (source-of-truth)
// - Manual shelves can use manualRange (wins) or priceRange
// - Final output is within ±BAND_POINTS of currentPriceAnchor
// - Manual shelves win on overlap (remove overlapping autos)
// - Manual shelves can override score via scoreOverride
// - Strength remap keeps shelves in 60–89 band
//
// Uses DEEP provider (jobs only), chart provider remains untouched.
//
// Efficient lookback plan (LOCKED for shelves):
// - 15m = 180 days
// - 30m = 180 days
// - 1h  = 180 days

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { computeShelves } from "../logic/smzShelvesScanner.js";
import { getBarsFromPolygonDeep } from "../../../api/providers/polygonBarsDeep.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUTFILE = path.resolve(__dirname, "../data/smz-shelves.json");
const MANUAL_FILE = path.resolve(__dirname, "../data/smz-manual-shelves.json");

// Config
const SYMBOL = "SPY";
const BAND_POINTS = 40;

// ✅ Lookback days (LOCKED for shelves)
const DAYS_15M = 180;
const DAYS_30M = 180;
const DAYS_1H = 180;

// Shelves strength band (LOCKED)
const SHELF_STRENGTH_LO = 60;
const SHELF_STRENGTH_HI = 89;

// ---------- helpers ----------
const isoNow = () => new Date().toISOString();
const round2 = (x) => Math.round(Number(x) * 100) / 100;

function clampInt(x, lo, hi) {
  const n = Math.round(Number(x));
  if (!Number.isFinite(n)) return lo;
  return Math.max(lo, Math.min(hi, n));
}

// Normalize Polygon aggregate bars to { time(sec), open, high, low, close, volume }
function normalizeBars(raw) {
  if (!Array.isArray(raw)) return [];
  return raw
    .map((b) => {
      const tms = Number(b.t ?? b.time ?? 0);
      const t = tms > 1e12 ? Math.floor(tms / 1000) : tms;
      return {
        time: t,
        open: Number(b.o ?? b.open ?? 0),
        high: Number(b.h ?? b.high ?? 0),
        low: Number(b.l ?? b.low ?? 0),
        close: Number(b.c ?? b.close ?? 0),
        volume: Number(b.v ?? b.volume ?? 0),
      };
    })
    .filter(
      (b) =>
        Number.isFinite(b.time) &&
        Number.isFinite(b.open) &&
        Number.isFinite(b.high) &&
        Number.isFinite(b.low) &&
        Number.isFinite(b.close)
    )
    .sort((a, b) => a.time - b.time);
}

function spanInfo(label, bars) {
  if (!Array.isArray(bars) || bars.length === 0) {
    console.log(`[SHELVES] COVERAGE ${label}: none`);
    return { first: null, last: null, spanDays: null };
  }

  const first = bars[0].time;
  const last = bars[bars.length - 1].time;
  const days = (last - first) / 86400;

  console.log(
    `[SHELVES] COVERAGE ${label}:`,
    "bars =", bars.length,
    "| from =", new Date(first * 1000).toISOString(),
    "| to =", new Date(last * 1000).toISOString(),
    "| spanDays =", days.toFixed(1)
  );

  return { first, last, spanDays: days };
}

function lastClose(bars) {
  if (!Array.isArray(bars) || !bars.length) return null;
  const c = bars[bars.length - 1]?.close;
  return Number.isFinite(c) ? c : null;
}

function pickCurrentPriceAnchor({ bars30m, bars1h }) {
  const c30 = lastClose(bars30m);
  const c1h = lastClose(bars1h);

  if (Number.isFinite(c30) && Number.isFinite(c1h)) {
    const diff = Math.abs(c30 - c1h);
    if (diff > 5) {
      console.warn("[SHELVES] WARNING: 30m vs 1h close mismatch:", { c30, c1h, diff });
    }
    return c30;
  }

  return Number.isFinite(c30) ? c30 : (Number.isFinite(c1h) ? c1h : null);
}

function normalizeRange(pr) {
  if (!Array.isArray(pr) || pr.length !== 2) return null;
  const a = Number(pr[0]);
  const b = Number(pr[1]);
  if (!Number.isFinite(a) || !Number.isFinite(b)) return null;
  const hi = round2(Math.max(a, b));
  const lo = round2(Math.min(a, b));
  if (!(hi > lo)) return null;
  return { hi, lo };
}

function overlapsBand(hi, lo, bandLow, bandHigh) {
  return hi >= bandLow && lo <= bandHigh;
}

function rangesOverlap(aHi, aLo, bHi, bLo) {
  return !(aHi < bLo || aLo > bHi);
}

function filterShelvesToBand(levels, currentPrice, bandPoints) {
  if (!Array.isArray(levels)) return [];
  if (!Number.isFinite(currentPrice)) return levels;

  const lo = currentPrice - bandPoints;
  const hi = currentPrice + bandPoints;

  return levels.filter((s) => {
    const r = normalizeRange(s?.priceRange);
    if (!r) return false;
    return overlapsBand(r.hi, r.lo, lo, hi);
  });
}

function remapShelvesStrengthToBand(levels, lo = SHELF_STRENGTH_LO, hi = SHELF_STRENGTH_HI) {
  if (!Array.isArray(levels) || levels.length === 0) {
    return { levels, minRaw: null, maxRaw: null };
  }

  const rawVals = levels
    .map((x) => Number(x?.strength))
    .filter((n) => Number.isFinite(n));

  if (rawVals.length === 0) {
    return { levels, minRaw: null, maxRaw: null };
  }

  const minRaw = Math.min(...rawVals);
  const maxRaw = Math.max(...rawVals);

  if (maxRaw === minRaw) {
    const mapped = levels.map((x) => ({
      ...x,
      strength_raw: Number(x?.strength ?? 0),
      strength: hi,
    }));
    return { levels: mapped, minRaw, maxRaw };
  }

  const mapped = levels.map((x) => {
    const raw = Number(x?.strength ?? 0);
    const t = (raw - minRaw) / (maxRaw - minRaw);
    const scaled = lo + (hi - lo) * t;
    const strength = clampInt(scaled, lo, hi);
    return { ...x, strength_raw: raw, strength };
  });

  return { levels: mapped, minRaw, maxRaw };
}

// ---------------- Manual shelves (source of truth) ----------------

function loadManualShelves() {
  if (!fs.existsSync(MANUAL_FILE)) {
    console.log(`[SHELVES] Manual shelves file not found (ok): ${MANUAL_FILE}`);
    return [];
  }
  try {
    const raw = fs.readFileSync(MANUAL_FILE, "utf8");
    const json = JSON.parse(raw);
    const arr = Array.isArray(json?.levels) ? json.levels : [];

    const out = arr
      .map((s) => {
        const type = String(s?.type ?? "").toLowerCase();
        if (type !== "accumulation" && type !== "distribution") return null;

        // ✅ manualRange wins (like institutions)
        const r = normalizeRange(
          Array.isArray(s?.manualRange) && s.manualRange.length === 2
            ? s.manualRange
            : s.priceRange
        );
        if (!r) return null;

        const price = round2((r.hi + r.lo) / 2);

        // scoreOverride optional
        const scoreOverride = Number.isFinite(Number(s?.scoreOverride))
          ? Number(s.scoreOverride)
          : null;

        // If override exists, use it; otherwise default into shelf band (will clamp)
        const strengthBase = scoreOverride ?? Number(s?.strength ?? 75);
        const strength = clampInt(strengthBase, SHELF_STRENGTH_LO, SHELF_STRENGTH_HI);

        return {
          type,
          price,
          priceRange: [r.hi, r.lo],
          // preserve manual metadata
          shelfKey: s?.shelfKey ?? null,
          locked: true,
          rangeSource: "manual",
          status: s?.status ?? "active",
          comment: typeof s?.comment === "string" ? s.comment : null,
          scoreOverride,
          strength,
          strength_source: scoreOverride != null ? "manual_override" : "manual_default",
        };
      })
      .filter(Boolean)
      .filter((s) => String(s.status).toLowerCase() !== "inactive");

    console.log(`[SHELVES] Manual shelves loaded: ${out.length} (${MANUAL_FILE})`);
    return out;
  } catch (e) {
    console.warn(`[SHELVES] Manual shelves failed to load: ${MANUAL_FILE} :: ${e?.message}`);
    return [];
  }
}

function removeAutosOverlappingManual(autoLevels, manualLevels) {
  if (!Array.isArray(autoLevels) || autoLevels.length === 0) return [];
  if (!Array.isArray(manualLevels) || manualLevels.length === 0) return autoLevels;

  let removed = 0;
  const out = autoLevels.filter((a) => {
    const ar = normalizeRange(a?.priceRange);
    if (!ar) return false;

    const overlaps = manualLevels.some((m) => {
      const mr = normalizeRange(m?.priceRange);
      if (!mr) return false;
      return rangesOverlap(ar.hi, ar.lo, mr.hi, mr.lo);
    });

    if (overlaps) removed++;
    return !overlaps;
  });

  if (removed) console.log(`[SHELVES] Autos removed due to manual overlap: ${removed}`);
  return out;
}

async function main() {
  try {
    console.log("[SHELVES] Fetching bars (DEEP)…");

    const [bars15mRaw, bars30mRaw, bars1hRaw] = await Promise.all([
      getBarsFromPolygonDeep(SYMBOL, "15m", DAYS_15M),
      getBarsFromPolygonDeep(SYMBOL, "30m", DAYS_30M),
      getBarsFromPolygonDeep(SYMBOL, "1h", DAYS_1H),
    ]);

    const bars15m = normalizeBars(bars15mRaw);
    const bars30m = normalizeBars(bars30mRaw);
    const bars1h = normalizeBars(bars1hRaw);

    console.log("[SHELVES] 15m bars:", bars15m.length);
    console.log("[SHELVES] 30m bars:", bars30m.length);
    console.log("[SHELVES] 1h  bars:", bars1h.length);

    const s15 = spanInfo("15m", bars15m);
    const s30 = spanInfo("30m", bars30m);
    const s1h = spanInfo("1h", bars1h);

    console.log("[SHELVES] last close 15m:", lastClose(bars15m));
    console.log("[SHELVES] last close 30m:", lastClose(bars30m));
    console.log("[SHELVES] last close 1h :", lastClose(bars1h));

    const currentPriceAnchor = pickCurrentPriceAnchor({ bars30m, bars1h });
    if (!Number.isFinite(currentPriceAnchor)) {
      throw new Error("Cannot determine currentPriceAnchor from 30m/1h bars");
    }

    console.log("[SHELVES] currentPriceAnchor (from 30m/1h):", currentPriceAnchor.toFixed(2));

    // 1) Manual shelves (source-of-truth)
    const manualAll = loadManualShelves();
    const manualInBand = filterShelvesToBand(manualAll, currentPriceAnchor, BAND_POINTS);

    // 2) Auto shelves (scanner)
    console.log("[SHELVES] Running shelves scanner (Acc/Dist)…");
    const shelvesRaw =
      computeShelves({
        bars10m: bars15m, // historical naming
        bars30m,
        bars1h,
        bandPoints: BAND_POINTS,
      }) || [];

    const shelvesBand = filterShelvesToBand(shelvesRaw, currentPriceAnchor, BAND_POINTS);

    console.log("[SHELVES] Shelves generated (auto raw):", shelvesRaw.length);
    console.log("[SHELVES] Shelves kept (auto band):", shelvesBand.length);
    console.log("[SHELVES] Shelves kept (manual band):", manualInBand.length);

    // 3) Manual wins overlap: remove overlapping autos
    const autoNoOverlap = removeAutosOverlappingManual(shelvesBand, manualInBand);

    // 4) Remap AUTO strengths into shelf band
    const { levels: autoMapped, minRaw, maxRaw } = remapShelvesStrengthToBand(
      autoNoOverlap,
      SHELF_STRENGTH_LO,
      SHELF_STRENGTH_HI
    );

    // 5) Manual already clamped + includes scoreOverride, comment, etc.
    const merged = [...manualInBand, ...autoMapped].slice(0, 12);

    console.log("[SHELVES] Strength remap:", {
      band: `${SHELF_STRENGTH_LO}-${SHELF_STRENGTH_HI}`,
      minRaw,
      maxRaw,
    });

    console.log(`[SHELVES] Emitting shelves: manual ${manualInBand.length} + auto ${autoMapped.length} = ${merged.length}`);
    console.log("[SHELVES] Saved shelves to:", OUTFILE);

    const payload = {
      ok: true,
      meta: {
        generated_at_utc: isoNow(),
        symbol: SYMBOL,
        band_points: BAND_POINTS,
        current_price_anchor: Number(currentPriceAnchor.toFixed(2)),
        lookback_days: { "15m": DAYS_15M, "30m": DAYS_30M, "1h": DAYS_1H },
        coverage: { "15m": s15, "30m": s30, "1h": s1h },
        strength_band: {
          lo: SHELF_STRENGTH_LO,
          hi: SHELF_STRENGTH_HI,
          min_raw: Number.isFinite(minRaw) ? Number(minRaw) : null,
          max_raw: Number.isFinite(maxRaw) ? Number(maxRaw) : null,
        },
        manual_file: path.basename(MANUAL_FILE),
        manual_loaded_in_band: manualInBand.length,
      },
      levels: merged,
    };

    fs.mkdirSync(path.dirname(OUTFILE), { recursive: true });
    fs.writeFileSync(OUTFILE, JSON.stringify(payload, null, 2), "utf8");

    console.log("[SHELVES] Job complete.");
  } catch (err) {
    console.error("[SHELVES] FAILED:", err);

    try {
      const fallback = {
        ok: true,
        levels: [],
        note: "SMZ shelves job error, no shelves generated this run",
      };
      fs.mkdirSync(path.dirname(OUTFILE), { recursive: true });
      fs.writeFileSync(OUTFILE, JSON.stringify(fallback, null, 2), "utf8");
      console.log("[SHELVES] Wrote fallback empty smz-shelves.json");
    } catch (inner) {
      console.error("[SHELVES] Also failed to write fallback smz-shelves.json:", inner);
    }

    process.exitCode = 1;
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

export default main;
