NEW FILES / FOLDERS ADDED YESTERDAY (FULL PATHS)

(Everything below is within /opt/render/project/src in the Render backend)

✅ 1. services/core/logic/smzEngine.js

Path:

/services/core/logic/smzEngine.js


Purpose:

This is the new Smart Money Zone Engine file.

This is the prototype of the institutional scoring logic we were building.

It replaced the old computeAccDistLevelsFromBars engine.

This file currently exports computeSmartMoneyLevels (or another function name, depending on last edit).

New teammate action:
→ Treat this file as a prototype. Reference the pass-over spec to rebuild cleanly.

✅ 2. services/core/jobs/updateSmzLevels.js

Path:

/services/core/jobs/updateSmzLevels.js


Purpose:

SMZ zone generator job.

Fetches bars (30m/1h/4h) via Polygon provider.

Calls the new SMZ engine.

Writes output to:

/services/core/data/smz-levels.json


New teammate action:
→ Confirm import path to polygonBars.js (we had errors here).
→ Confirm which engine function is imported (computeSmartMoneyLevels).

⚠️ 3. services/core/polygon/polygonBars.js (NEW FOLDER + FILE)

Path (created yesterday):

/services/core/polygon/polygonBars.js


Purpose:

This was introduced because the new SMZ job expected a Polygon fetcher inside /services/core/polygon/.

This folder DID NOT previously exist.

The file was created to satisfy the missing import error:

Cannot find module 'services/core/polygon/polygonBars.js'


This file mirrors the provider in /api/providers/polygonBars.js.

⚠️ Important note:
This folder is redundant with the real provider at:

/api/providers/polygonBars.js


A backend dev should consolidate these to avoid confusion.

⚠️ 4. services/core/routes/smzLevels.js (NEW ROUTE FILE)

Path:

/services/core/routes/smzLevels.js


Purpose:

Provides the API endpoint:

GET /api/v1/smz-levels


Reads from services/core/data/smz-levels.json

Sends JSON for the frontend overlay.

New teammate action:
→ Ensure this route is correctly imported into services/core/server.js.

⚠️ 5. Modified: services/core/server.js (NEW MOUNT POINTS)

Path:

/services/core/server.js


New additions introduced yesterday:

import smzLevels from "./routes/smzLevels.js";

app.use("/api/v1/smz-levels", smzLevels);


This patch must be cleaned up so:

Import order is correct,

app is defined before use,

No duplicate route declarations occur.

⚠️ 6. services/core/data/smz-levels.json

Path:

/services/core/data/smz-levels.json


Purpose:

Output file generated by updateSmzLevels.js.

Consumed by frontend overlay.

JSON structure:

{
  "ok": true,
  "levels": [ ... ]
}

⚠️ 7. (Added But Should Be Cleaned Up): services/core/polygon/ FOLDER

This folder did not exist before.
We created it only because import paths were failing.

The REAL polygon provider is in:

/api/providers/polygonBars.js


Your new backend teammate should:

Remove the duplicate polygon folder,

Or consolidate logic into one canonical polygon provider.

📌 SUMMARY LIST (for the new teammate)
Type	Path	Status	Notes
New file	/services/core/logic/smzEngine.js	Prototype	Needs full rebuild following pass-over spec
New file	/services/core/jobs/updateSmzLevels.js	Prototype	Must be cleaned up; correct provider imports
New file	/services/core/routes/smzLevels.js	Working	Route must be mounted cleanly
New folder	/services/core/polygon/	Temporary	Should NOT exist long-term
New file	/services/core/polygon/polygonBars.js	Temporary	Replace with /api/providers/polygonBars.js
Modified	/services/core/server.js	Works, but sloppy	Needs cleanup around app.use(...)
New output	/services/core/data/smz-levels.json	Good	Consumer of SMZ engine
🎯 WHAT A NEW BACKEND DEV MUST DO FIRST

Here’s the step-by-step reality map for the teammate:

1. Clean the folder structure

Use ONE polygon provider:

/api/providers/polygonBars.js


Delete or ignore:

/services/core/polygon/polygonBars.js


Update all imports accordingly.

2. Rebuild smzEngine.js clean from scratch

Using the Institutional Algo Spec from the pass-over.

Ignore all prototype logic currently in the file.

3. Rebuild updateSmzLevels.js clean from scratch

Requirements:

Fetch bars via polygonBars provider:

getBarsFromPolygon(symbol, timeframe, days)


Pass bars into:

computeSmartMoneyLevels(bars30m, bars1h, bars4h)


Write:

/services/core/data/smz-levels.json

4. Ensure stable fetch window

Use:

30m → last 90–120 days

1h → last 120–150 days

4h → last 150–180 days

Polygon URL builder must support this.

5. Ensure route is clean
app.use("/api/v1/smz-levels", smzLevels);


Only once.
After app is defined.

6. Test job via shell
node services/core/jobs/updateSmzLevels.js


Confirm output:

30m returns ~1000 bars

1h returns ~500 bars

4h returns ~300 bars

Zones: 6–9

7. Validate visual match

Compare dashboard output to the TradingView reference chart provided in screenshots.

🎉 YES — with this document, a new backend teammate can 100% take over

And be able to:

Understand what you want

Understand what exists

Know what’s broken

Know what to delete

Know what to rebuild

Know how to integrate it into the dashboard

This is the handoff they need.
