// services/core/logic/engine3/v5/canonical/engine3ReasonCodes.js
//
// Engine 3 v5 — Canonical reason-code helpers.
//
// Contract:
// - Pure helper module.
// - Centralizes stable Engine 3 v5 reason-code vocabulary.
// - Does not calculate price action.
// - Does not calculate control.
// - Does not publish canonical direction.
// - Does not create permission.
// - Does not create execution.
//
// Purpose:
// Keep reason-code wording consistent across v5 modules so
// diagnostics, Replay, Engine 28A, and future teammates can trace
// exactly which stage produced a decision.

export const ENGINE3_V5_REASON_CODES = Object.freeze({
  // General
  SHADOW_READ_ONLY:
    "ENGINE3_V5_SHADOW_READ_ONLY",

  NO_PERMISSION_CREATED:
    "ENGINE3_V5_NO_PERMISSION_CREATED",

  NO_EXECUTION:
    "ENGINE3_V5_NO_EXECUTION",

  NO_CANONICAL_DIRECTION_CREATED:
    "ENGINE3_V5_NO_CANONICAL_DIRECTION_CREATED",

  // Engine 26 / location
  EXACT_NEGOTIATED_ZONE_AVAILABLE:
    "ENGINE3_V5_EXACT_NEGOTIATED_ZONE_AVAILABLE",

  EXACT_NEGOTIATED_ZONE_MISSING:
    "ENGINE3_V5_EXACT_NEGOTIATED_ZONE_MISSING",

  ENGINE26_EVALUATION_AUTHORIZED:
    "ENGINE3_V5_ENGINE26_EVALUATION_AUTHORIZED",

  ENGINE26_EVALUATION_NOT_AUTHORIZED:
    "ENGINE3_V5_ENGINE26_EVALUATION_NOT_AUTHORIZED",

  ENGINE26_DIRECTION_DIAGNOSTIC_ONLY:
    "ENGINE3_V5_ENGINE26_DIRECTION_DIAGNOSTIC_ONLY",

  ZONE_EVALUATION_ELIGIBLE:
    "ENGINE3_V5_ZONE_EVALUATION_ELIGIBLE",

  ZONE_EVALUATION_NOT_ELIGIBLE:
    "ENGINE3_V5_ZONE_EVALUATION_NOT_ELIGIBLE",

  // Timeframe authority
  ONE_MINUTE_DIAGNOSTIC_ONLY:
    "ENGINE3_V5_1M_IMMEDIATE_DIAGNOSTIC_ONLY",

  FORMING_FIVE_MINUTE_DIAGNOSTIC_ONLY:
    "ENGINE3_V5_FORMING_5M_DIAGNOSTIC_ONLY",

  COMPLETED_FIVE_MINUTE_MATURE_AUTHORITY:
    "ENGINE3_V5_COMPLETED_5M_PRIMARY_MATURE_REACTION_AUTHORITY",

  TEN_MINUTE_CONTEXT_ONLY:
    "ENGINE3_V5_10M_BROADER_CONTEXT_ONLY",

  // Control
  BUYERS_CONTROL:
    "ENGINE3_V5_CONTROL_STATE_BUYERS_CONTROL",

  SELLERS_CONTROL:
    "ENGINE3_V5_CONTROL_STATE_SELLERS_CONTROL",

  CONTESTED:
    "ENGINE3_V5_CONTROL_STATE_CONTESTED",

  ABSORPTION:
    "ENGINE3_V5_CONTROL_STATE_ABSORPTION",

  NO_CONTROL:
    "ENGINE3_V5_CONTROL_STATE_NO_CONTROL",

  // Canonical direction
  CANONICAL_LONG:
    "ENGINE3_V5_CANONICAL_DIRECTION_LONG",

  CANONICAL_SHORT:
    "ENGINE3_V5_CANONICAL_DIRECTION_SHORT",

  CANONICAL_NEUTRAL:
    "ENGINE3_V5_CANONICAL_DIRECTION_NEUTRAL",

  STATE_MACHINE_SOLE_DIRECTION_AUTHORITY:
    "ENGINE3_V5_STATE_MACHINE_SOLE_DIRECTION_AUTHORITY",

  // State transitions
  ESTABLISHED_BY_COMPLETED_5M:
    "ENGINE3_V5_COMPLETED_5M_ESTABLISHED_CANONICAL_DIRECTION",

  REVERSED_BY_COMPLETED_5M:
    "ENGINE3_V5_COMPLETED_5M_REVERSED_CANONICAL_DIRECTION",

  REINFORCED_BY_COMPLETED_5M:
    "ENGINE3_V5_COMPLETED_5M_REINFORCED_CANONICAL_DIRECTION",

  WAITING_FOR_MATURE_COMPLETED_5M_CONTROL:
    "ENGINE3_V5_WAITING_FOR_MATURE_COMPLETED_5M_CONTROL",

  // Departure / travel
  DEPARTURE_CONFIRMED:
    "ENGINE3_V5_DEPARTURE_CONFIRMED",

  DEPARTURE_NOT_CONFIRMED:
    "ENGINE3_V5_DEPARTURE_NOT_CONFIRMED",

  DEPARTURE_CANNOT_CREATE_DIRECTION_FROM_NEUTRAL:
    "ENGINE3_V5_DEPARTURE_CANNOT_CREATE_DIRECTION_FROM_NEUTRAL",

  EMA10_TRAVEL_ACTIVE:
    "ENGINE3_V5_EMA10_TRAVEL_ACTIVE",

  EMA10_TRAVEL_INACTIVE:
    "ENGINE3_V5_EMA10_TRAVEL_INACTIVE",

  EMA10_CANNOT_CREATE_DIRECTION:
    "ENGINE3_V5_EMA10_CANNOT_CREATE_DIRECTION",

  EMA10_CANNOT_REVERSE_DIRECTION:
    "ENGINE3_V5_EMA10_CANNOT_REVERSE_DIRECTION",

  // Canonical publication
  CANONICAL_CONTRACT_BUILT:
    "ENGINE3_V5_CANONICAL_CONTRACT_BUILT",

  REACTION_CONFIRMED:
    "ENGINE3_V5_REACTION_CONFIRMED",

  REACTION_NOT_CONFIRMED:
    "ENGINE3_V5_REACTION_NOT_CONFIRMED",

  NOT_AUTHORIZED_FOR_ENGINE4:
    "ENGINE3_V5_NOT_AUTHORIZED_FOR_ENGINE4",

  NOT_AUTHORIZED_FOR_ENGINE6:
    "ENGINE3_V5_NOT_AUTHORIZED_FOR_ENGINE6",
});

export function uniqueReasonCodes(values = []) {
  return [
    ...new Set(
      (Array.isArray(values) ? values : [])
        .filter(Boolean)
        .map((value) => String(value))
    ),
  ];
}

export function canonicalDirectionReasonCode(
  direction
) {
  const text = String(direction || "")
    .trim()
    .toUpperCase();

  if (text === "LONG") {
    return ENGINE3_V5_REASON_CODES.CANONICAL_LONG;
  }

  if (text === "SHORT") {
    return ENGINE3_V5_REASON_CODES.CANONICAL_SHORT;
  }

  return ENGINE3_V5_REASON_CODES.CANONICAL_NEUTRAL;
}

export function controlStateReasonCode(
  controlState
) {
  const text = String(controlState || "")
    .trim()
    .toUpperCase();

  if (text === "BUYERS_CONTROL") {
    return ENGINE3_V5_REASON_CODES.BUYERS_CONTROL;
  }

  if (text === "SELLERS_CONTROL") {
    return ENGINE3_V5_REASON_CODES.SELLERS_CONTROL;
  }

  if (text === "CONTESTED") {
    return ENGINE3_V5_REASON_CODES.CONTESTED;
  }

  if (text === "ABSORPTION") {
    return ENGINE3_V5_REASON_CODES.ABSORPTION;
  }

  return ENGINE3_V5_REASON_CODES.NO_CONTROL;
}

export default ENGINE3_V5_REASON_CODES;
