name: ohlc-archive

on:
  workflow_dispatch:
  # Align with 10-min schedule so chart DVR matches meter DVR
  schedule:
    - cron: "*/10 13-19 * * 1-5"
    - cron: "0 20 * * 1-5"

concurrency:
  group: data-writes-main
  cancel-in-progress: false

jobs:
  ohlc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Sync repo state
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Archive OHLC
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          ARCHIVE_SYMBOLS: ${{ vars.ARCHIVE_SYMBOLS || 'SPY,QQQ' }}
          ARCHIVE_TIMEFRAMES: "10m,1h,1d"
          LOOKBACK_BARS: "500"
        run: |
          python scripts/archive_ohlc.py

      - name: Show saved files
        run: |
          echo "--- tree data/archive/ohlc ---"
          ls -R data/archive/ohlc || true

      - name: Commit & push (retry-safe)
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "OHLC replay snapshot: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || git commit --allow-empty -m "OHLC keepalive"

          # Retry-safe push: if rejected, rebase onto latest main and push again
          for attempt in 1 2 3; do
            if git push origin HEAD:main; then
              echo "Push succeeded on attempt $attempt"
              break
            fi
            echo "Push rejected; syncing with origin/main (attempt $attempt)..."
            git fetch origin main
            git rebase origin/main
          done
